services:

  mysql-flask-app-container:
    image: mysql:9.0.1
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: .
    links:
      - mysql-flask-app-container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mysql-flask-app-container
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    labels:
      - "autoheal=true"
    healthcheck:
        test: curl --fail http://localhost:5000/ || exit 1
        interval: 40s
        timeout: 30s
        retries: 3
        start_period: 60s
    
  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    restart: always
    environment:
      - AUTOHEAL_INTERVAL=60
      - AUTOHEAL_START_PERIOD=300
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes: 
  mysql-data: