services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: __init__.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
    command: ./entrypoint.sh  # Llama al script de entrada
